### ISSUE TITLE
動作しない

### ISSUE THREAD

**Issue by Sayamame-beans** [taizan-hokuto/yvi#1]
```python
import yvi
info = yvi.get_info(video_id = "Q3unv8bSGms")
print(info.get_title())
```
このような、yviを用いた単純なプログラムであっても、以下のエラーメッセージを出力し、動作しません。
(一部パス省略)
```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    info = yvi.get_info(video_id = "Q3unv8bSGms")
  File "~\lib\site-packages\yvi\yvi.py", line 194, in get_info
    return VideoInfo(video_id = video_id, session = session)
  File "~\lib\site-packages\yvi\yvi.py", line 91, in __init__
    self._parse(text)
  File "~\lib\site-packages\yvi\yvi.py", line 101, in _parse
    self._res = json.loads(result.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```
向こう側に仕様変更でもあったんでしょうか...

環境:
OS: Windows8.1
Chrome: 84.0.4147.135
Python: 3.7.7

**Comment by taizan-hokuto** [comment]
youtube側で仕様変更があったようです。ちかいうちに修正します。

**Comment by taizan-hokuto** [comment]
v0.0.3で修正しました。
pip install --upgrade yvi
を実行してみてください。

**Comment by Sayamame-beans** [comment]
対応ありがとうございます！
無事解決しました！
